name: Code Quality

on: push

jobs:
    validate-code:
        name: Validate Code
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install Dependencies
              run: |-
                  npm install

            - name: Run Linters
              run: |-
                  npm run lint

            - name: Run Unit Tests
              run: |-
                  npm run test:ci
