name: Code Quality

on: push

jobs:
    validate-code:
        name: Validate Code
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install Dependencies
              run: |-
                  npm install

            - name: Run Linters
              run: |-
                  npm lint

            - name: Run Unit Tests
              run: |-
                  npm test
